### ISSUE TITLE
Chromosome X phasing

### ISSUE THREAD

**Issue by dtaliun** [atgu/hgdp_tgp#9]
Thank you very much for creating amazing resources! 

Quick question: do you plan to release phased chromosome X any time soon?

Thanks again!

**Comment by z-koenig** [comment]
Yes, this is in the works! Our current timeline has a release coming before the end of December.

**Comment by dtaliun** [comment]
Hi,
I wanted to follow up and ask if you have any updates on chromosome X. Related question: I see that there is phased chromosome X data inside `gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes/`; what is the difference between phased_haplotypes and phased_haplotypes_v2?
Thanks again for the resource!

**Comment by LindoNkambule** [comment]
Hi @dtaliun , we are wrapping up phasing of chromosome X. I'll ping you here once it's available for download.

Regarding the difference, we had phased the first release without pedigree information and this affected phasing/imputation performance when compared to NYGC 1KG. Pedigree was incorporated in v2, which achieves better phasing/imputation compared to NYGC 1KG panel as we show in the [manuscript](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9900804/). We also filtered out singletons in v2, you'll notice a drop in the number of variants compared to the first release.

**Comment by LindoNkambule** [comment]
Hi @dtaliun , the phased chromosome X files are now available for download and can be found here:
`gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes_v2/hgdp1kgp_chrX*`

**Comment by dtaliun** [comment]
Hi @LindoNkambule,

Thank you very much for sharing the phased chromosome X! I appreciate all your hard work.

I started to use the data, but I found a few thousand variants on the chrX non-PAR region where male samples were phased as heterozygous. Here are a few examples of heterozygous genotypes in male samples in the phased output:
HG00881 is  1|0 for chrX:2855315:C/T
HG02011,NA20866, and NA20903 are 1|0 for chrX:3443944:A/G

I believe this may be related to the [bug in shapeit5](https://github.com/odelaneau/shapeit5/issues/100#issue-2259306156), where shapeit5 doesn't set these het genotypes to missing correctly.

Could you please investigate on your end?

Thanks again!

**Comment by LindoNkambule** [comment]
Hi @dtaliun,

Thank you for raising this issue. I will look into it.

**Comment by dtaliun** [comment]
Hi @LindoNkambule,

I just wanted to follow up on the chromosome X phased files. Something is not right about them.

Unlike autosomal chromosome files, they also include monomorphic variants and singletons. Moreover, the **hgdp1kgp_chrX_par1.shapeit5_common.bcf** and **hgdp1kgp_chrX_par2.shapeit5_common.bcf** files have no variants with AC>=2:

```
bcftools view -H -c2 -C8180 hgdp1kgp_chrX_par1.shapeit5_common.bcf | wc -l
# outputs 1 entry
bcftools view -H -c2 -C8180 hgdp1kgp_chrX_par2.shapeit5_common.bcf | wc -l
# outputs 1 entry
```

**Comment by Ahhgust** [comment]
Sorry to jump in, but I too am looking for the X data. Like most folks, I'm interested in the non-par regions of the X, but what is posted are just rare variants, whereas for the autosomes you get rare+common variants.
I'm hoping that maybe the final X dataset just isn't posted? Or perhaps shapeit5 doesn't play nice w/ the X.
For my purposes, I'm just interested in making a panel for phasing/imputation, in which case maybe there are enough males where I can get enough "phased" haplotypes from the original VCF to make it work.

**Comment by LindoNkambule** [comment]
Hi everyone, the issues pointed have been addressed, I will post an update once the files have been made public.

One caveat, cc @dtaliun : to address the issue pointed out by @dtaliun , we decided to code the males as homozygous in non-PAR region. However, there were still a few variants where males were being phased as heterozygous (see [issue](https://github.com/odelaneau/shapeit5/issues/100#issuecomment-2368600638)). Since this was a small number (~7K), we decided to filter them out in the meantime while we wait for the SHAPEIT5 developers to look into the issue.

**Comment by dtaliun** [comment]
Hi @LindoNkambule, 

Thank you very much for fixing it! And thank you again for sharing all this valuable data with us!

**Comment by aabiddanda** [comment]
Hi @LindoNkambule just wanted to follow-up on whether the common variants for the non-PAR chrX regions have been uploaded to GCP? I just looked and they do not seem to be uploaded in the same location on GCP?

**Comment by LindoNkambule** [comment]
Hi everyone,

Apologies for the delay. We have updated the chrX phased files. The paths haven't changed, the phased files can be found at gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes_v2/. Please let me know if you encounter any issues/spot problems with the resource, your help is appreciated!

Thanks!
Lindo

**Comment by ahasuni** [comment]
Hello there @LindoNkambule, just wanted to follow up on this. I still dont see common snps for chrX non par in this google storage directory: gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes_v2/

I see gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes_v2/hgdp1kgp_chrX_non_par.full.shapeit5_rare.bcf which I believe is just rare variants according to the name.

Hasuni

**Comment by LindoNkambule** [comment]
Hi @ahasuni,

We received a similar question not long ago. The naming is a bit confusing but the file contains all variants, we phased common variants and used this as a scaffold to phase rare variants. I am attaching a plot of the variant counts in the chrX non-par

![Image](https://github.com/user-attachments/assets/de464918-59a5-47e5-a300-2da5f503c6aa)

**Comment by ahasuni** [comment]
Hi there, thank you for sharing these plots and clarifying the naming convention. 

I am a little confused by this plot. What exactly do the 6 and 17 mean on the bars? What does the dark red mean? This may be a silly question but what exactly do the log10(count) represent? Also I was expecting to see snps with MAF between 0.2 and 0.5. Is there a reason why no such snps are being shown in the plot?

**Comment by Ahhgust** [comment]
Hmm. I have to agree that the y-axis looks a bit suspect. (it appears to be log-scaled, but the label suggests it's a linear scale of the log count). 
Regardless, I downloaded the hgdp1kgp_chrX_non_par.full.shapeit5_rare.bcf from gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes_v2/ and can confirm that their are *no* sites with >20% minor allele frequency. Eg, the commands:
`bcftools view -H -q 0.20 -Q 0.80 hgdp1kgp_chrX_non_par.full.shapeit5_rare.bcf | wc -l`
returns 0 records, whereas the X dataset without phasing has ~160k records in it (same command). 
Are we sure that we have the right URL?

**Comment by LindoNkambule** [comment]
Hi everyone,

I used log count to avoid bins with large counts taking most of the space. The text (counts) are the actual variant counts when MAF is computed in two different ways: (1) not considering ploidy and (2) considering ploidy (males are haploid) - factoring this in when computing MAF. 

I agree that there might be an issue and am looking into it. Could you share the path to the chrX unphased dataset you're referring to @Ahhgust .

gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes_v2 is the correct path

**Comment by Ahhgust** [comment]
Sure. I'm referring to the unphased dataset made available by gnomad:
https://gnomad.broadinstitute.org/downloads#v3-hgdp-1kg
which includes genotype calls on the X.

**Comment by ahasuni** [comment]
Hi there @LindoNkambule, just wanted to follow up on this to see if there are any updates?

**Comment by LindoNkambule** [comment]
Hi everyone, apologies for the delayed response. I have managed to trace down the cause of the problem: the variants were getting dropped due to the HWE filter applied before phasing. This issue has been addressed but I am now encountering an issue with SHAPEIT5 outputting heterozygous males in the non-PAR region, working on finding a workaround this. I will provide another update soon and hopefully have the fixed file published to the public buckets soon too.

Thanks,
Lindo

**Comment by LindoNkambule** [comment]
Hi everyone, the chrX files have been updated and can be found here: gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes_v2/ . Please let me know if you spot any issues, your questions have been helpful in debugging some of the issues.

Thanks,
Lindo

**Comment by aabiddanda** [comment]
Hi @LindoNkambule - I just checked the updated version for some phasing + imputation on chrX and it looks great so far - includes all the allele frequencies as far as I can tell and passes all my sanity checks. Thanks so much for generating this!
